"""empty message

Revision ID: 6109da58bf5a
Revises: 27a903174924
Create Date: 2020-03-20 19:24:23.853225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6109da58bf5a'
down_revision = '27a903174924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('items')
    op.drop_table('coupons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('deliverer', sa.VARCHAR(), nullable=False),
    sa.Column('coupon', sa.VARCHAR(), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('tip_percent', sa.INTEGER(), nullable=True),
    sa.Column('tip_absolute', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('deliverer', sa.VARCHAR(), nullable=False),
    sa.Column('arrival', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
